[package]
name = "tcpbin"
description = "Simple library/CLI providing TCP echo server"
version = "0.1.2"
edition = "2024"
rust-version = "1.91"
readme = "README.md"
repository = "https://github.com/DoumanAsh/tcpbin"
license = "BSL-1.0"
include = [
    "**/*.rs",
    "Cargo.toml",
    "README.md",
    "LICENSE"
]

[dependencies]
ha_proxy_protocol = "0.2.3"

[dependencies.tracing]
version = "0.1"
optional = true

[dependencies.tokio]
version = "1"
features = ["net", "time", "io-util", "rt"]
optional = true

[dependencies.arg]
version = "0.4"
features = ["std"]
optional = true

[[bin]]
name = "tcpbin"
path = "src/main.rs"
required-features = ["cli"]

[features]
tracing = ["dep:tracing"]
tokio = ["dep:tokio"]
cli = ["arg", "tokio?/macros"]

[profile.release]
lto = 'thin'
opt-level = 3
codegen-units = 1
strip = true
debug = false

[package.metadata.docs.rs]
features = ["tokio"]
